#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "AntialiasingParams.h"

layout(local_size_x = 32, local_size_y = 32) in;

layout(binding = 0, r11f_g11f_b10f) readonly uniform image2D previousTarget;
layout(binding = 1) uniform sampler2D previousDepthImage;
layout(binding = 2, r11f_g11f_b10f) uniform image2D currentTarget;
layout(binding = 3) uniform sampler2D currentDepthImage;

layout(binding = 4) readonly uniform params_t
{
  AntialiasingParams params;
};


void main() {
    
}