#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

#include "AntialiasingParams.h"

layout(local_size_x = 32, local_size_y = 32) in;

layout(binding = 0, r11f_g11f_b10f) readonly uniform image2D previousTarget;
layout(binding = 1) uniform sampler2D previousDepthImage;
layout(binding = 2, r11f_g11f_b10f) uniform image2D currentTarget;
layout(binding = 3) uniform sampler2D currentDepthImage;
layout(binding = 4, rg16f) readonly uniform image2D velocityImage;

layout(binding = 5) readonly uniform params_t
{
  AntialiasingParams params;
};

void main()
{
  const ivec2 resolution = imageSize(previousTarget);

  const ivec2 currentTexCoord = ivec2(gl_GlobalInvocationID.xy);
  const vec2 currentUVTexCoord = vec2(currentTexCoord) / vec2(resolution);

  if (currentTexCoord.x >= resolution.x && currentTexCoord.y >= resolution.y)
  {
    return;
  }

  const float currentDepth = texture(currentDepthImage, currentUVTexCoord).x;

  // const vec4 screenSpacePosition = vec4(currentUVTexCoord * 2.0 - 1.0, currentDepth, 1.0);

  // vec4 worldSpacePosition = (params.currentInvProjView * screenSpacePosition);
  // worldSpacePosition /= worldSpacePosition.w;

  // vec4 previousProjectedCoords = (params.previousProjView * vec4(worldSpacePosition.xyz, 1.0));
  // previousProjectedCoords /= previousProjectedCoords.w;

  const vec2 velocityUVCorrection = imageLoad(velocityImage, currentTexCoord).xy;
  const vec2 previousUVTexCoord =
    currentUVTexCoord + velocityUVCorrection; // 0.5 * previousProjectedCoords.xy + 0.5;

  const ivec2 previousTexCoord = ivec2(previousUVTexCoord * vec2(resolution));

  if (previousUVTexCoord.x != clamp(previousUVTexCoord.x, 0.0, 1.0))
  {
    return;
  }

  if (previousUVTexCoord.y != clamp(previousUVTexCoord.y, 0.0, 1.0))
  {
    return;
  }

  const float previousDepth = texture(previousDepthImage, previousUVTexCoord).x;

  if (abs(previousDepth - currentDepth) > params.depthCutoff)
  {
    return;
  }

  vec3 minColor = vec3(10000.0);
  vec3 maxColor = vec3(-10000.0);

  // vec2 texelSize = 1.0 / vec2(resolution);

  for (int x = -1; x <= 1; x++)
  {
    for (int y = -1; y <= 1; y++)
    {
      vec3 color = imageLoad(currentTarget, currentTexCoord + ivec2(x, y)).xyz;
      minColor = min(minColor, color);
      maxColor = max(maxColor, color);
    }
  }

  const vec4 previousFrame = imageLoad(previousTarget, previousTexCoord);

  const vec3 previousFrameClamped = clamp(previousFrame.xyz, minColor, maxColor);

  const vec4 currentFrame = imageLoad(currentTarget, currentTexCoord);

  const vec4 result = params.previousFrameUsage * vec4(previousFrameClamped, 1.0) +
    (1.0 - params.previousFrameUsage) * currentFrame;

  imageStore(currentTarget, currentTexCoord, result);
}
