#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 32, local_size_y = 32) in;

layout(binding = 0, r32f) uniform image2D gOcclusion;

void main()
{
  const ivec2 resolution = imageSize(gOcclusion);

  const ivec2 currentTexCoord = ivec2(gl_GlobalInvocationID.xy);

  if (currentTexCoord.x >= resolution.x || currentTexCoord.y >= resolution.y)
  {
    return;
  }

  float result = 0.0;

  int range = 2;
  int count = 0;

  for (int x = -range; x < range; x++)
  {
    for (int y = -range; y < range; y++)
    {
      result += imageLoad(gOcclusion, currentTexCoord + ivec2(x, y)).x;
      count++;
    }
  }

  result /= float(count);

  imageStore(gOcclusion, currentTexCoord, vec4(result, result, result, 1));
}
