#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 32, local_size_y = 32) in;

layout(binding = 0, rgba16_snorm) readonly uniform image2D gNormal;
layout(binding = 1) uniform sampler2D gDepth;
layout(binding = 2, r32f) writeonly uniform image2D gOcclusion;
layout(binding = 3) uniform sampler2D nouseTexture;

layout(binding = 4) readonly buffer kernel_t
{
  vec3 kernel[];
};

layout(push_constant) uniform push_constant_t
{
  uint kernelSize;
};

void main() {}
