#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 32, local_size_y = 32) in;

layout(binding = 0, rgba16_snorm) readonly uniform image2D gNormal;
layout(binding = 1) uniform sampler2D gDepth;
layout(binding = 2, r32f) writeonly uniform image2D gOcclusion;
layout(binding = 3) uniform sampler2D noiseTexture;

layout(binding = 4) readonly buffer kernel_t
{
  vec4 kernel[];
};
layout(binding = 5) readonly uniform matrices_t
{
  mat4 projMatrix;
  mat4 invProjMatrix;
  mat4 invViewMatrix;
};

layout(push_constant) uniform push_constant_t
{
  uint kernelSize;
  float radius;
  float occlusionPower;
};

vec3 getViewPosFromDepth(vec2 texCoord, float depth)
{
  const vec4 screenSpacePosition = vec4(texCoord * 2.0 - 1.0, depth, 1.0);

  vec4 viewSpacePosition = invProjMatrix * screenSpacePosition;
  viewSpacePosition /= viewSpacePosition.w;

  return viewSpacePosition.xyz;
}

void main()
{
  const ivec2 resolution = imageSize(gOcclusion);

  const ivec2 currentTexCoord = ivec2(gl_GlobalInvocationID.xy);
  const vec2 currentUVTexCoord = vec2(currentTexCoord) / vec2(resolution);

  if (currentTexCoord.x >= resolution.x || currentTexCoord.y >= resolution.y)
  {
    return;
  }

  const float depth = texture(gDepth, currentUVTexCoord).x;
  const vec3 viewSpacePosition = getViewPosFromDepth(currentUVTexCoord, depth);

  const vec3 normal = normalize(imageLoad(gNormal, currentTexCoord).xyz);
  const vec3 viewSpaceNormal = normalize((transpose(invViewMatrix) * vec4(normal, 0.0)).xyz);

  const vec2 noiseScale = vec2(resolution) / vec2(textureSize(noiseTexture, 0));

  const vec3 randomVector = vec3(texture(noiseTexture, currentUVTexCoord * noiseScale).xy, 0.0);
  const vec3 tangent =
    normalize(randomVector - viewSpaceNormal * dot(randomVector, viewSpaceNormal));
  const vec3 bitangent = cross(viewSpaceNormal, tangent);

  const mat3 transformMatrix = mat3(tangent, bitangent, viewSpaceNormal);

  float occlusion = 0.0;

  for (uint i = 0; i < kernelSize; i++)
  {
    vec3 samplePos = transformMatrix * (kernel[i].xyz);
    samplePos = samplePos * radius + viewSpacePosition;

    const vec3 sampleDir = normalize(samplePos - viewSpacePosition);
    const float NdotS = max(dot(viewSpaceNormal, sampleDir), 0);

    vec4 offset = projMatrix * vec4(samplePos, 1.0);
    offset /= offset.w;
    const vec2 offsetTexCoord = offset.xy * 0.5 + 0.5;

    const float viewSpaceSampleDepth = getViewPosFromDepth(offsetTexCoord, texture(gDepth, offsetTexCoord).x).z;

    float range = smoothstep(0.0, 1.0, radius / abs(viewSpacePosition.z - viewSpaceSampleDepth));

    occlusion += range * step(viewSpaceSampleDepth, samplePos.z) * NdotS;
  }

  occlusion = 1.0 - (occlusion / kernelSize);
  float finalOcclusion = pow(occlusion, occlusionPower);

  imageStore(gOcclusion, currentTexCoord, vec4(finalOcclusion, finalOcclusion, finalOcclusion, 1));
}
